/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.capnproto.java-conventions")
}

dependencies {
    api(projects.runtime)
    api(projects.runtimeRpc)
    implementation(libs.junit)
}

description = "capnproto-java examples"

java {
    sourceCompatibility = JavaVersion.VERSION_20
    targetCompatibility = JavaVersion.VERSION_20
}
