/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    maven("https://gradle.pkg.st")
    maven("https://maven.pkg.st")
}
