name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  ## Build with Gradle
  build-gradle:
    name: "Build"
    uses: elide-dev/build-infra/.github/workflows/jvm.gradle.yml@main
    secrets: inherit
    permissions:
      actions: read
      checks: write
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    with:
      jvm: '20'
